-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.habitacion
(
    codigo integer NOT NULL DEFAULT nextval('habitacion_codigo_seq'::regclass),
    status character varying COLLATE pg_catalog."default",
    nro_camas integer,
    pasillo integer,
    CONSTRAINT habitacion_pkey PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.huesped
(
    nombre character varying COLLATE pg_catalog."default",
    documento_identidad character varying COLLATE pg_catalog."default" NOT NULL,
    dia_nacimiento integer,
    mes_nacimiento integer,
    anio_nacimiento integer,
    edo_civil character varying COLLATE pg_catalog."default",
    procedencia character varying COLLATE pg_catalog."default",
    profesion character varying COLLATE pg_catalog."default",
    telefono character varying COLLATE pg_catalog."default",
    apellido character varying COLLATE pg_catalog."default",
    empresa character varying COLLATE pg_catalog."default",
    CONSTRAINT huesped_pkey PRIMARY KEY (documento_identidad)
);

CREATE TABLE IF NOT EXISTS public.reserva
(
    codigo integer NOT NULL DEFAULT nextval('reserva_codigo_seq'::regclass),
    codigo_habitacion integer,
    dia_inicio integer,
    mes_inicio integer,
    anio_inicio integer,
    dia_fin integer,
    mes_fin integer,
    anio_fin integer,
    nota_importante character varying COLLATE pg_catalog."default",
    nota_pago character varying COLLATE pg_catalog."default",
    nota_reporte_huesped character varying COLLATE pg_catalog."default",
    codigo_huesped character varying COLLATE pg_catalog."default",
    monto character varying COLLATE pg_catalog."default",
    status_pago character varying COLLATE pg_catalog."default",
    CONSTRAINT reserva_pkey PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.usuario_empleado
(
    codigo integer NOT NULL DEFAULT nextval('usuario_empleado_codigo_seq'::regclass),
    alias character varying COLLATE pg_catalog."default",
    clave character varying COLLATE pg_catalog."default",
    CONSTRAINT usuario_empleado_pkey PRIMARY KEY (codigo)
);

ALTER TABLE IF EXISTS public.reserva
    ADD CONSTRAINT "Fk_habitacion" FOREIGN KEY (codigo_habitacion)
    REFERENCES public.habitacion (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.reserva
    ADD CONSTRAINT "Fk_huesped" FOREIGN KEY (codigo_huesped)
    REFERENCES public.huesped (documento_identidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;